language: erlang
notifications:
        email: github-contact@mr-pi.de
env:
        - APPNAME='euser'
        - AUTOMODULE='euser_mainServer'
        - ENVIRONMENT='erlang'
otp_release:
        - R16B
        - R15B03
        - R15B02
        - R15B01
        - R15B
        - R14B04
        - R14B03
        - R14B02
